export default {
  ADD: 'ADD',
  SET: 'SET',
  SET_DAYS: 'SET_DAYS',
  FETCH_DAYS: 'FETCH_DAYS',
  FETCH_DAY: 'FETCH_DAY',
  DELETE_RECORD: 'DELETE_RECORD',
  DELETE_DAYS: 'DELETE_DAYS',
  DELETE_DAY: 'DELETE_DAY',
  EDIT_RECORD: 'EDIT_RECORD',
};